vars:

  long-description: &long-description |
      AWS CloudTrail is a service that enables governance, compliance,
      operational auditing, and risk auditing of your AWS account. It can log,
      continuously monitor and retain account activity related to actions across
      your AWS infrastructure. CloudTrail provides event history of your AWS
      account, including actions taken from the management console, command line
      interface (CLI), AWS SDKs, and APIs. As a security best practice, you need
      to be aware of all configuration changes performed at the CloudTrail level
      to prevent configuration mistakes or tampering that would prevent detailed
      logging in your AWS account.

  description: &description |
      This policy ensures that actions taken against the AWS CloudTrail service
      are quickly identified, and can be evaluated to ensure that they are
      appropriate. Configuration changes to your CloudTrail service can be a
      standard change, or could be a sign of tampering in an attempt to hide
      evidence of malicious activity.

  violation-desc: &violation-desc |
      The AWS service in your account has had its configuration changed, and
      this activity should be reviewed to ensure that it is expected and
      appropriate to your environment.

  action-desc: &action-desc |
      AWS CloudTrail is a critical component to ensure the security and
      compliance of your AWS infrastructure. As such, an e-mail notification has
      been sent to the event-owner and resource-owner for this CloudTrail
      service to investigate the activity is expected and appropriate.

  subject: &subject "AWS CloudTrail - Configuration Change Identified - [custodian {{ account }} - {{ region }}]"

  mailer-queue: &mailer-queue https://sqs.{region}.amazonaws.com/{account}/cloud-custodian-mailer




policies:


##########################################################################
#####   AWS.CLOUDTRAIL CONFIGURATION CHANGE                          #####
##########################################################################



################################
## CloudTrail mode policy     ##
################################


- name: aws-cloudtrail-configuration-changes
  tags:
    - Category::Security
    - Compliance::APRA
    - Compliance::MAS
    - Compliance::NIST 800-53
    - Risk::High
  metadata:
      long-description: *long-description
  resource: cloudtrail
  mode:
    type: cloudtrail
    events:
        - source: cloudtrail.amazonaws.com
          event: CreateTrail
          ids: "responseElements.trailARN"
        - source: cloudtrail.amazonaws.com
          event: UpdateTrail
          ids: "responseElements.trailARN"
        - source: cloudtrail.amazonaws.com
          event: DeleteTrail
          ids: "responseElements.trailARN"
        - source: cloudtrail.amazonaws.com
          event: AddTags
          ids: "responseElements.trailARN"
        - source: cloudtrail.amazonaws.com
          event: RemoveTags
          ids: "responseElements.trailARN"
        - source: cloudtrail.amazonaws.com
          event: PutEventSelectors
          ids: "responseElements.trailARN"
        - source: cloudtrail.amazonaws.com
          event: StartLogging
          ids: "responseElements.trailARN"
        - source: cloudtrail.amazonaws.com
          event: StopLogging
          ids: "responseElements.trailARN"
  actions:
      - type: notify
        template: default.html
        priority_header: 1
        subject: *subject
        violation_desc: *violation-desc
        action_desc: *action-desc
        to:
            - resource-owner
            - event-owner
        transport:
            type: sqs
            queue: *mailer-queue
            region: {region}
